project:
  type: website
  output-dir: docs

# Meta
description-meta: "Personal website for Emi Cervantes"
author-meta: "Emi Cervantes"

website:
  title: "Emi Cervantes"
  image: "https://quarto.org/quarto.png"
  description: "Quarto Academic Website Template adapted by Dr. Gang He"
 
  navbar:
  #  background: "#f2a65a"  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About  # Comment the Group part out to remove the Group page
        href: about.qmd           
      - text: Research
        href: research.qmd                              
      - text: Outreach
        href: outreach.qmd

    right: 
      - text: CV
        href: files/emi-cv.pdf
      #- icon: github
       # href: https://github.com/emicervantes
       # target: _blank
      #- icon: linkedin
       # href: https://www.linkedin.com/in/emicervantes/
       # target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Emi Cervantes](https://emicervantes.github.io/) &copy; <script>document.write(new Date().getFullYear())</script>" 
    right:  
      - icon: github
        href: https://github.com/emicervantes
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/emicervantes/emicervantes.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://emicervantes.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

